workspace:
  base: /go
  path: src/github.com/drone/drone-cli

pipeline:
  test:
    image: golang:1.8
    commands:
      - echo starting
      - cd drone
      - go test

  build:
    image: golang:1.8
    commands: sh .drone.sh

  snapshot:
    image: plugins/docker
    repo: mark86092/drone-cli
    tag: 0.7
    secrets: [docker_username, docker_password]
    when:
      branch: 0.7
      event: push
